### ISSUE TITLE
Travis should use GHC 8.2.2

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/Drasil#672]
It is using 8.0.2, which is getting old now. And we risk having issues between our own local builds if we're too far out of sync.

**Comment by JacquesCarette** [comment]
@szymczdm please feel free to delegate.

**Comment by szymczdm** [comment]
@samm82 Do you think you can handle this? I know you've been playing with the packages and whatnot. If you need help, just let me know.

**Comment by JacquesCarette** [comment]
I've merged that. Can you take a look at the Travis logs tomorrow to see if it did indeed work?

**Comment by szymczdm** [comment]
I took a quick look and I still see 8.0.2 in the log as of 55314562012d8876a5de414dd36964c6. Looks like the fix may not be that simple.

I'm pretty sure it's because we're not using GHC directly, but instead are getting stack to use a custom ghc version. We may need to update the stack yaml file to force the resolver to the correct version (we're currently using the LTS of 8.0.2, there's an LTS for 8.2.2 available, but we can tell it to use a custom ghc version instead as well).

I'll take a quick crack at it to see if I can get it working.

**Comment by samm82** [comment]
What's the status on this @szymczdm?

**Comment by JacquesCarette** [comment]
As per the comments above, we shouldn't rush to 8.4.3 quite yet. 8.2.2 for now will do.

**Comment by szymczdm** [comment]
@samm82 I believe you've already switched us to 8.2.2 on your SubPackages branch (when you swapped to LTS-11.2), so once we merge that in we're done.

**Comment by samm82** [comment]
@szymczdm Perfect 👍

**Comment by samm82** [comment]
@szymczdm Does this mean that the TravisVersion branch can be closed?
